=== AltyFox/bsqmods/shared/schemas/Mod.schema.base.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Mod.schema.base.json",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": ["string", "null"]
    },
    "id": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "pattern": "^(?<=^v?|\\sv?)(?:(?:0|[1-9]\\d{0,9}?)\\.){2}(?:0|[1-9]\\d{0,9})(?:-(?:--+)?(?:0|[1-9]\\d*|\\d*[a-z]+\\d*)){0,100}(?=$| |\\+|\\.)(?:(?<=-\\S+)(?:\\.(?:--?|[\\da-z-]*[a-z-]\\d*|0|[1-9]\\d*)){1,100}?)?(?!\\.)(?:\\+(?:[\\da-z]\\.\\?-?){1,100}?(?!\\w))?(?!\\+)$",
      "flags": "i"
    },
    "author": {
      "type": ["string", "null"]
    },
    "authorIcon": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "modloader": {
      "type": "string",
      "enum": ["QuestLoader", "Scotland2"]
    },
    "download": {
      "type": "string",
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "source": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "cover": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "funding": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri",
        "pattern": "^(http|https)://.*$",
        "flags": "i"
      }
    },
    "website": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    }
  },
  "required": ["name", "id", "version", "modloader", "download", "funding"]
}

=== AltyFox/bsqmods/mods/1.24.0/BeatmapPlayCount-0.1.0.json
{
  "name": "Simple Beatmap Play Count",
  "description": null,
  "id": "BeatmapPlayCount",
  "version": "0.1.0",
  "author": "Netux",
  "authorIcon": "https://avatars.githubusercontent.com/u/6181929?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/netux/BeatSaber-BeatmapPlayCount-Quest/releases/download/v0.1.0/BeatmapPlayCount.v0.1.0.qmod",
  "source": "https://github.com/netux/BeatSaber-BeatmapPlayCount-Quest/",
  "cover": null,
  "funding": [],
  "website": "https://github.com/netux/BeatSaber-BeatmapPlayCount-Quest/"
}

=== AltyFox/bsqmods/mods/1.17.1/ImageCoverExpander-0.1.4.json
{
  "name": "ImageCoverExpander",
  "description": "Expands the Cover Image to the full right side of the song select menu!",
  "id": "ImageCoverExpander",
  "version": "0.1.4",
  "author": "Millzy and Raine",
  "authorIcon": null,
  "modloader": "QuestLoader",
  "download": "https://millzydev.itch.io/imgcoverexp-quest",
  "source": null,
  "cover": null,
  "funding": [],
  "website": null
}

=== AltyFox/bsqmods/mods/1.28.0_4124311467/scorepercentage-3.2.1.json
{
  "name": "Score Percentage",
  "description": "shows extra information after completing a level",
  "id": "scorepercentage",
  "version": "3.2.1",
  "author": "Polly51104",
  "authorIcon": "https://avatars.githubusercontent.com/u/56835953?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/Royston1999/ScorePercentage-Quest/releases/download/v3.2.1/ScorePercentage_v3.2.1.qmod",
  "source": "https://github.com/Royston1999/ScorePercentage-Quest/",
  "cover": "https://raw.githubusercontent.com/Royston1999/ScorePercentage-Quest/master/Cover.jpg",
  "funding": [],
  "website": null
}

=== AltyFox/bsqmods/mods/1.37.0_9064817954/NoodleExtensions-1.5.4.json
{
  "name": "NoodleExtensions",
  "description": "This adds a host of new things you can do with your maps. Original mod for PC by Aeroluna. Contributions by Fern and Sc2ad.",
  "id": "NoodleExtensions",
  "version": "1.5.4",
  "author": "StackDoubleFlow",
  "authorIcon": "https://avatars.githubusercontent.com/u/22183359?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/bsq-ports/NoodleExtensions/releases/download/v1.5.4/NoodleExtensions.qmod",
  "source": "https://github.com/bsq-ports/NoodleExtensions/",
  "cover": "https://raw.githubusercontent.com/bsq-ports/NoodleExtensions/master/cover.png",
  "funding": [],
  "website": "https://github.com/bsq-ports/NoodleExtensions/"
}

=== AltyFox/bsqmods/mods/1.28.0_4124311467/ImageFactory-1.0.2.json
{
  "name": "ImageFactory",
  "description": "Place and customize images throughout your game.",
  "id": "ImageFactory",
  "version": "1.0.2",
  "author": "Optimus",
  "authorIcon": "https://avatars.githubusercontent.com/u/69561711?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/OptimusChen/ImageFactory-Quest/releases/download/v1.0.2/ImageFactory.qmod",
  "source": "https://github.com/OptimusChen/ImageFactory-Quest/",
  "cover": "https://raw.githubusercontent.com/OptimusChen/ImageFactory-Quest/master/cover.png",
  "funding": [],
  "website": null
}

=== AltyFox/bsqmods/mods/1.17.1/Slogans-0.1.4.json
{
  "name": "Slogans",
  "description": "Adds some funky customisable text in the sky",
  "id": "Slogans",
  "version": "0.1.4",
  "author": "Millzy",
  "authorIcon": null,
  "modloader": "QuestLoader",
  "download": "https://millzydev.itch.io/slogans",
  "source": null,
  "cover": null,
  "funding": [],
  "website": null
}

=== AltyFox/bsqmods/mods/1.27.0_3631150051/sabertailor-2.0.0.json
{
  "name": "Saber Tailor",
  "description": "Edit controller settings for each saber independently. Also includes Kinsi's Controller Settings Helper mod",
  "id": "sabertailor",
  "version": "2.0.0",
  "author": "Polly51104",
  "authorIcon": "https://avatars.githubusercontent.com/u/56835953?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/Royston1999/Saber-Tailor-quest/releases/download/v2.0.0/SaberTailor_v2.0.0.qmod",
  "source": "https://github.com/Royston1999/Saber-Tailor-quest/",
  "cover": "https://raw.githubusercontent.com/Royston1999/Saber-Tailor-quest/master/Cover.png",
  "funding": [],
  "website": null
}

=== AltyFox/bsqmods/mods/1.24.0/lapiz-0.0.7.json
{
  "name": "Lapiz",
  "description": "Lapiz makes modders' lives easier by exposing utilities to them cleanly. This mod does nothing on it's own.",
  "id": "lapiz",
  "version": "0.0.7",
  "author": "Raine",
  "authorIcon": "https://avatars.githubusercontent.com/u/64136899?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/raineaeternal/Lapiz/releases/download/v0.0.7/Lapiz.qmod",
  "source": "https://github.com/raineaeternal/Lapiz/",
  "cover": null,
  "funding": [],
  "website": "https://github.com/raineaeternal/Lapiz/"
}
