=== AltyFox/bsqmods/shared/schemas/Mod.schema.base.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Mod.schema.base.json",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": ["string", "null"]
    },
    "id": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "pattern": "^(?<=^v?|\\sv?)(?:(?:0|[1-9]\\d{0,9}?)\\.){2}(?:0|[1-9]\\d{0,9})(?:-(?:--+)?(?:0|[1-9]\\d*|\\d*[a-z]+\\d*)){0,100}(?=$| |\\+|\\.)(?:(?<=-\\S+)(?:\\.(?:--?|[\\da-z-]*[a-z-]\\d*|0|[1-9]\\d*)){1,100}?)?(?!\\.)(?:\\+(?:[\\da-z]\\.\\?-?){1,100}?(?!\\w))?(?!\\+)$",
      "flags": "i"
    },
    "author": {
      "type": ["string", "null"]
    },
    "authorIcon": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "modloader": {
      "type": "string",
      "enum": ["QuestLoader", "Scotland2"]
    },
    "download": {
      "type": "string",
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "source": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "cover": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "funding": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri",
        "pattern": "^(http|https)://.*$",
        "flags": "i"
      }
    },
    "website": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    }
  },
  "required": ["name", "id", "version", "modloader", "download", "funding"]
}

=== AltyFox/bsqmods/mods/1.17.1/hitscore-2.3.0.json
{
  "name": "Hit Score Visualizer",
  "description": "Changes the scores that pop up when you hit notes.",
  "id": "hitscore",
  "version": "2.3.0",
  "author": "Christoffyw and Metalit",
  "authorIcon": "https://avatars.githubusercontent.com/u/55860414?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/Christoffyw/HitScoreVisualizer/releases/download/2.3.0/HitScoreVisualizer_v2.3.0.qmod",
  "source": "https://github.com/Christoffyw/HitScoreVisualizer/",
  "cover": "https://raw.githubusercontent.com/Christoffyw/HitScoreVisualizer/master/Cover.jpg",
  "funding": [],
  "website": null
}

=== AltyFox/bsqmods/mods/1.13.0/PinkCore-1.3.1.json
{
  "name": "PinkCore",
  "description": "PinkCore, formerly known as PinkUtils is a core mod that ports over many required features which ensures a smooth PC-Like experience.",
  "id": "PinkCore",
  "version": "1.3.1",
  "author": "Pink, StackDoubleFlow, Lillie, RedBrumbler",
  "authorIcon": null,
  "modloader": "QuestLoader",
  "download": "https://github.com/BSMGPink/PinkUtils/releases/download/1.3.1/PinkCorev1.3.1.zip",
  "source": "https://github.com/BSMGPink/PinkUtils/",
  "cover": "https://raw.githubusercontent.com/BSMGPink/PinkUtils/master/cover.png",
  "funding": [],
  "website": null
}

=== AltyFox/bsqmods/mods/1.26.2/NoParticles-0.1.7.json
{
  "name": "NoParticles",
  "description": "Allows you to disable various particles throughout the game",
  "id": "NoParticles",
  "version": "0.1.7",
  "author": "AllyPallyUK, KodenameKRAK",
  "authorIcon": "https://avatars.githubusercontent.com/u/106346717?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/kodenamekrak/NoParticles/releases/download/0.1.7/NoParticles.qmod",
  "source": "https://github.com/kodenamekrak/NoParticles/",
  "cover": "https://raw.githubusercontent.com/kodenamekrak/NoParticles/master/cover.png",
  "funding": [],
  "website": "https://github.com/kodenamekrak/NoParticles/"
}

=== AltyFox/bsqmods/mods/1.28.0_4124311467/trick-saber-0.0.1.json
{
  "name": "Trick Saber",
  "description": "Mod that lets you throw and spin your sabers every which way you want!",
  "id": "trick-saber",
  "version": "0.0.1",
  "author": "RedBrumbler",
  "authorIcon": "https://avatars.githubusercontent.com/u/91820572?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/NuggoDEV/TrickSaber-1.28.0/releases/download/0.0.1/Tricksaber.qmod",
  "source": "https://github.com/NuggoDEV/TrickSaber-1.28.0/",
  "cover": "https://raw.githubusercontent.com/NuggoDEV/TrickSaber-1.28.0/master/cover.png",
  "funding": [],
  "website": null
}

=== AltyFox/bsqmods/mods/1.24.0/ImageCoverExpander-0.2.1.json
{
  "name": "ImageCoverExpander",
  "description": "Expands the Cover Image to the full right side of the song select menu!",
  "id": "ImageCoverExpander",
  "version": "0.2.1",
  "author": "Millzy and Raine",
  "authorIcon": "https://avatars.githubusercontent.com/u/64136899?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/raineio/ImageCoverExpander-Quest/releases/download/0.2.2/ImageCoverExpander.qmod",
  "source": "https://github.com/raineio/ImageCoverExpander-Quest/",
  "cover": null,
  "funding": [],
  "website": null
}

=== AltyFox/bsqmods/mods/1.16.4/feetsaber-0.1.1.json
{
  "name": "feetsaber",
  "description": "i got bored",
  "id": "feetsaber",
  "version": "0.1.1",
  "author": "Phaze#6193 | Publisher: nesiLLL",
  "authorIcon": null,
  "modloader": "QuestLoader",
  "download": "https://github.com/phaze-the-dumb/feetsaber/releases/download/v1.0.0/feetsaber.qmod",
  "source": "https://github.com/phaze-the-dumb/feetsaber/",
  "cover": null,
  "funding": [],
  "website": null
}

=== AltyFox/bsqmods/mods/1.21.0/jdfixer-2.0.0.json
{
  "name": "JDFixer",
  "description": "Configure your Jump Distance, Speed, and more with ultra precision!",
  "id": "jdfixer",
  "version": "2.0.0",
  "author": "Metalit",
  "authorIcon": "https://avatars.githubusercontent.com/u/48568911?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/Metalit/QuestJDFixer/releases/download/v2.0.0/JDFixer.qmod",
  "source": "https://github.com/Metalit/QuestJDFixer/",
  "cover": "https://raw.githubusercontent.com/Metalit/QuestJDFixer/master/cover.png",
  "funding": [],
  "website": null
}

=== AltyFox/bsqmods/mods/1.28.0_4124311467/gaysabers-0.1.0.json
{
  "name": "GaySabers",
  "description": "Makes your sabers gay (i mean glow in rainbow colors)",
  "id": "gaysabers",
  "version": "0.1.0",
  "author": "hdgamer1404Jonas",
  "authorIcon": null,
  "modloader": "QuestLoader",
  "download": "https://github.com/jxnxsdev/GaySabers/releases/download/0.1.0/GaySabers.qmod",
  "source": "https://github.com/jxnxsdev/GaySabers/",
  "cover": "https://raw.githubusercontent.com/jxnxsdev/GaySabers/master/logo.gif",
  "funding": [],
  "website": null
}
